media: assets/images

content:
  - name: events
    label: Events
    type: collection
    path: 'content/posts'
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          format: MMM-do
      - name: draft
        label: Published
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text
        options:
          media: post_images