media: assets/images

content:
  - name: events
    label: Events
    type: collection
    path: 'content/events'
    view:
      fields: [ title, published, date ]
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: draft
        label: Published
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text
        options:
          media: post_images