media: assets/images

content:
  - name: home
    label: Home Page
    type: file
    path: 'content/homeSettings.yaml'
    fields:
    - {name: headline, label: Headline, type: string, required: false}
    - {name: cover , label: Cover Image , type: image}
    - name: sections
      label: Page Sections
      type: block
      list: true # Often used with type: block to allow multiple sections
      blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
      blocks:
        - name: hero
          label: Add Hero Section
          component: hero # Assumes a 'hero' component is defined and that its type is `object`
        - name: text
          label: Add Text Block
          fields:
            - name: content
              label: Text Content
              type: rich-text
  - name: events
    label: Events
    type: collection
    path: 'content/events'
    view: {fields: [ title, draft, date ], primary: title, sort: [ date, title, draft ]}
    fields:
      - name: title
        label: Event Name
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - {name: draft, label: Draft?,type: boolean, default: true}
      - name: eventImage
        label: Event Image
        type: image
        path: '/eventPosters'
        media: '/eventPosters'
      - {name: eventLink, label: Event Link, type: string}
      - name: body
        label: Event Description
        type: rich-text
        options:
          media: post_images
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: draft
        label: Draft?
        type: boolean
        default: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Body
        type: rich-text
        options:
          media: post_images
  - name: performers
    label: Performers
    type: collection
    path: 'content/performers'
    fields:
      - name: name
        label: Name
        type: string
      - name: date
        label: Date Joined
        type: date
      - name: description
        label: Quote
        type: text
      - name: body
        label: Biography
        type: rich-text
        options:
          media: post_images

settings:
  hide: true


