media: assets/images

content:
  - name: events
    label: Events
    type: collection
    path: 'content/events'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Event Name
        type: string
      - name: draft
        label: Draft?
        type: boolean
        default: true
      - name: body
        label: Event Description
        type: rich-text
        options:
          media: post_images
      - name: event_details
        label: Event Details
        type: object
        fields:
          - name: date
            label: Date
            type: date
            options:
              time: true
              format: yyyy-MM-dd'T'HH:mm:ss
          - name: location
            label: Location
            type: string
          - name: last_name
            label: Last name
            type: string
          - name: email
            label: Email address
            type: string
          - name: phone
            label: Phone number
            type: string
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: draft
        label: Draft?
        type: boolean
        default: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Body
        type: rich-text
        options:
          media: post_images
  - name: performers
    label: Performers
    type: collection
    path: 'content/performers'
    fields:
      - name: name
        label: Name
        type: string
      - name: date
        label: Date Joined
        type: date
      - name: description
        label: Quote
        type: text
      - name: body
        label: Biography
        type: rich-text
        options:
          media: post_images
