baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'No Duds Improv'
theme = "dudsTheme"

[menus]

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Events'
    pageRef = '/events'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
